# BOOLEAN INDEXING

In [2]:
import numpy as np

In [6]:
names = np.array(['Bob','Will','Joe','Bob', 'Will', 'Joe', 'Joe'])
names

array(['Bob', 'Will', 'Joe', 'Bob', 'Will', 'Joe', 'Joe'], dtype='<U4')

In [7]:
np.unique(names) #returns the sorted unique elements 

array(['Bob', 'Joe', 'Will'], dtype='<U4')

In [26]:
names == "saad"

array([False, False, False, False, False, False, False])

In [27]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [9]:
data = np.random.randn(7, 4)
data

array([[ 0.29932737,  0.96367431,  0.13085813, -0.23743639],
       [ 1.12305968, -0.88297542, -0.58623166,  1.80788778],
       [ 0.58322855,  0.20475104,  1.09196575, -1.25441056],
       [ 0.00523465,  0.05211967, -0.3896895 , -0.20068327],
       [-1.07450747, -0.61522562,  0.40719161, -1.40837081],
       [-1.31009935, -0.99860628,  0.13561688,  2.06214202],
       [-0.01056784, -0.96057351, -1.16194934, -0.20016147]])

In [36]:
bol = np.array([True,False,False,False,False,True,False],dtype ="bool")
data[bol] #now we have made boolean array so when its true it prints that data

array([[-0.5325994 ,  0.40827662,  0.02045338, -0.61983101],
       [ 1.4996328 , -2.1769711 , -2.82928776, -0.440613  ]])

In [30]:
data>1 #it shows answer in boolean true false

array([[False, False, False, False],
       [False, False, False, False],
       [False,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [ True, False, False, False],
       [False,  True, False,  True]])

In [31]:
data[data>1] #now only values are shown that are true 

array([1.04577103, 1.4996328 , 1.28539449, 1.68512368])

In [32]:
print(names == "Bob")
data[names=="Bob"]

[ True False False  True False False False]


array([[-0.5325994 ,  0.40827662,  0.02045338, -0.61983101],
       [-0.35156838, -1.13031117,  0.61320476, -0.76099294]])

In [40]:
condition = names!="Bob"

In [41]:
data[condition]

array([[-0.60232216, -0.11562615,  0.79362671, -0.63042149],
       [-0.20379878,  1.04577103,  0.3719129 ,  0.00376748],
       [ 0.54057807, -0.5569774 , -1.0001992 , -0.797905  ],
       [ 1.4996328 , -2.1769711 , -2.82928776, -0.440613  ],
       [-0.6793125 ,  1.28539449, -0.64420008,  1.68512368]])

In [42]:
data[~condition] #~true -> false, false -> true

array([[-0.5325994 ,  0.40827662,  0.02045338, -0.61983101],
       [-0.35156838, -1.13031117,  0.61320476, -0.76099294]])

In [44]:
data[~condition,1:3]

array([[ 0.40827662,  0.02045338],
       [-1.13031117,  0.61320476]])

In [55]:
data = np.arange(28).reshape(7,4)
data

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

In [53]:
cond = (names == "Bob") | (names == "Joe")
cond

array([ True,  True, False,  True, False,  True,  True])

In [54]:
data[cond]

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [12, 13, 14, 15],
       [20, 21, 22, 23],
       [24, 25, 26, 27]])

# FANCY INDEXING

In [56]:
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
arr

array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [57]:
arr[[1,2,3]]

array([[1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.]])

In [59]:
arr[[4,0,1,7]]

array([[4., 4., 4., 4.],
       [0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [7., 7., 7., 7.]])

In [61]:
arr[[4,0,1,7],[2,3,0,1]] #pair (4,2) , (0,3), (1,0) , (7,1)

array([4., 0., 1., 7.])

In [65]:
arr = np.arange(32).reshape(8,4)
print(arr)
arr[[1,5,7,2]][:,[0,3,1,2]]
# 1[0,3,1,2],5[0,3,1,2],7[0,3,1,2],2[0,3,1,2] ---> (1,0),(1,3),(1,1),(1,2)()()()()........

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [66]:
arr.T

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [68]:
arr.transpose()

array([[ 0,  4,  8, 12, 16, 20, 24, 28],
       [ 1,  5,  9, 13, 17, 21, 25, 29],
       [ 2,  6, 10, 14, 18, 22, 26, 30],
       [ 3,  7, 11, 15, 19, 23, 27, 31]])

In [69]:
remainder, whole_part = np.modf(arr)

In [71]:
remainder

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [72]:
whole_part

array([[ 0.,  1.,  2.,  3.],
       [ 4.,  5.,  6.,  7.],
       [ 8.,  9., 10., 11.],
       [12., 13., 14., 15.],
       [16., 17., 18., 19.],
       [20., 21., 22., 23.],
       [24., 25., 26., 27.],
       [28., 29., 30., 31.]])

In [75]:
names = np.unique(names)
names

array(['Bob', 'Joe', 'Will'], dtype='<U4')

## CONCATENATING

In [80]:
arr1 = np.arange(1,7).reshape(2,3)
arr1

array([[1, 2, 3],
       [4, 5, 6]])

In [82]:
arr2 = np.arange(7,13).reshape(2,3)
arr2

array([[ 7,  8,  9],
       [10, 11, 12]])

In [83]:
np.concatenate([arr1,arr2]) #by default axis is 0

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [84]:
np.concatenate([arr1,arr2],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [85]:
np.concatenate([arr1,arr2],axis=1)

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

STACK

In [86]:
np.stack([arr1,arr2])

array([[[ 1,  2,  3],
        [ 4,  5,  6]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

In [87]:
np.vstack([arr1,arr2]) #rows increase

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [88]:
np.hstack([arr1,arr2]) #columns increase

array([[ 1,  2,  3,  7,  8,  9],
       [ 4,  5,  6, 10, 11, 12]])

In [91]:
arr = np.arange(36).reshape(6,6)
arr

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [92]:
np.vsplit(arr,3)

[array([[ 0,  1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10, 11]]), array([[12, 13, 14, 15, 16, 17],
        [18, 19, 20, 21, 22, 23]]), array([[24, 25, 26, 27, 28, 29],
        [30, 31, 32, 33, 34, 35]])]

In [93]:
np.hsplit(arr,3) 

[array([[ 0,  1],
        [ 6,  7],
        [12, 13],
        [18, 19],
        [24, 25],
        [30, 31]]), array([[ 2,  3],
        [ 8,  9],
        [14, 15],
        [20, 21],
        [26, 27],
        [32, 33]]), array([[ 4,  5],
        [10, 11],
        [16, 17],
        [22, 23],
        [28, 29],
        [34, 35]])]

## FILING

In [12]:
ar1 = np.arange(6)

In [13]:
np.save("myarray.npy",ar1)

In [14]:
np.load("myarray.npy") #extension is necessary in load

array([0, 1, 2, 3, 4, 5])

In [15]:
ar2 = np.arange(8)

In [16]:
np.savez("twoarrays",x=ar1,y=ar2)

In [17]:
dic = np.load("twoarrays.npz")

In [18]:
ar11 = dic['x']
ar11

array([0, 1, 2, 3, 4, 5])

In [19]:
x=dic.files 
x

['x', 'y']